services:
  discogs_rec_model:
      build: src/
      volumes:
        - ./data:/data
        - ./src:/src
      environment:
        PYTHONPATH: /src
      command: ["python", "main.py"]
  discogs_rec_app:
    build: app/
    ports:
      - "8000:8000"
      - "8501:8501"
    volumes:
      - ./data:/data
    environment:
      PYTHONPATH: /app